# Generated by Django 5.1.3 on 2024-12-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=32)),
                ('QUALIFICATION', models.CharField(max_length=32)),
                ('GENDER', models.CharField(max_length=32)),
                ('YOP', models.IntegerField()),
                ('AGE', models.IntegerField()),
                ('SKILLS', models.CharField(max_length=32)),
                ('DOB', models.DateTimeField()),
                ('ADDRESS', models.CharField(max_length=32)),
                ('MOCK_RATING', models.CharField(max_length=32)),
                ('DEPARTMENT', models.CharField(max_length=32)),
            ],
        ),
    ]
