# Generated by Django 5.1.3 on 2024-12-06 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='DOB',
        ),
    ]
