# Generated by Django 5.1.3 on 2024-12-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sd', '0002_remove_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(default='2024-12-06'),
            preserve_default=False,
        ),
    ]
